# coding: utf-8

class Phoneme:
    phn_num = 90   # 1+48+41
    phn_list = (
        'sil',
        
        'CNaa',
        'CNaar',
        'CNae',
        'CNah',
        'CNao',
        'CNax',
        'CNay',
        'CNb',
        'CNc',
        'CNch',
        'CNd',
        'CNea',
        'CNee',
        'CNeh',
        'CNei',
        'CNf',
        'CNg',
        'CNh',
        'CNib',
        'CNih',
        'CNil',
        'CNiy',
        'CNiz',
        'CNizh',
        'CNj',
        'CNk',
        'CNl',
        'CNm',
        'CNn',
        'CNng',
        'CNoe',
        'CNoh',
        'CNp',
        'CNq',
        'CNr',
        'CNs',
        'CNsh',
        'CNt',
        'CNub',
        'CNul',
        'CNuw',
        'CNvl',
        'CNvw',
        'CNw',
        'CNx',
        'CNy',
        'CNz',
        'CNzh',

        'ENaa',
        'ENae',
        'ENah',
        'ENao',
        'ENaw',
        'ENax',
        'ENaxr',
        'ENay',
        'ENb',
        'ENch',
        'ENd',
        'ENdh',
        'ENeh',
        'ENer',
        'ENey',
        'ENf',
        'ENg',
        'ENhh',
        'ENih',
        'ENiy',
        'ENjh',
        'ENk',
        'ENl',
        'ENm',
        'ENn',
        'ENng',
        'ENow',
        'ENoy',
        'ENp',
        'ENr',
        'ENs',
        'ENsh',
        'ENt',
        'ENth',
        'ENuh',
        'ENuw',
        'ENv',
        'ENw',
        'ENy',
        'ENz',
        'ENzh',
    )
    phn_dict = {
        'sil': 0,
        
        'CNaa': 1,
        'CNaar': 2,
        'CNae': 3,
        'CNah': 4,
        'CNao': 5,
        'CNax': 6,
        'CNay': 7,
        'CNb': 8,
        'CNc': 9,
        'CNch': 10,
        'CNd': 11,
        'CNea': 12,
        'CNee': 13,
        'CNeh': 14,
        'CNei': 15,
        'CNf': 16,
        'CNg': 17,
        'CNh': 18,
        'CNib': 19,
        'CNih': 20,
        'CNil': 21,
        'CNiy': 22,
        'CNiz': 23,
        'CNizh': 24,
        'CNj': 25,
        'CNk': 26,
        'CNl': 27,
        'CNm': 28,
        'CNn': 29,
        'CNng': 30,
        'CNoe': 31,
        'CNoh': 32,
        'CNp': 33,
        'CNq': 34,
        'CNr': 35,
        'CNs': 36,
        'CNsh': 37,
        'CNt': 38,
        'CNub': 39,
        'CNul': 40,
        'CNuw': 41,
        'CNvl': 42,
        'CNvw': 43,
        'CNw': 44,
        'CNx': 45,
        'CNy': 46,
        'CNz': 47,
        'CNzh': 48,

        'ENaa': 49,
        'ENae': 50,
        'ENah': 51,
        'ENao': 52,
        'ENaw': 53,
        'ENax': 54,
        'ENaxr': 55,
        'ENay': 56,
        'ENb': 57,
        'ENch': 58,
        'ENd': 59,
        'ENdh': 60,
        'ENeh': 61,
        'ENer': 62,
        'ENey': 63,
        'ENf': 64,
        'ENg': 65,
        'ENhh': 66,
        'ENih': 67,
        'ENiy': 68,
        'ENjh': 69,
        'ENk': 70,
        'ENl': 71,
        'ENm': 72,
        'ENn': 73,
        'ENng': 74,
        'ENow': 75,
        'ENoy': 76,
        'ENp': 77,
        'ENr': 78,
        'ENs': 79,
        'ENsh': 80,
        'ENt': 81,
        'ENth': 82,
        'ENuh': 83,
        'ENuw': 84,
        'ENv': 85,
        'ENw': 86,
        'ENy': 87,
        'ENz': 88,
        'ENzh': 89,
    }
    
    @staticmethod
    def phn2idx(phn):
        return Phoneme.phn_dict.get(phn, 0)
    
    @staticmethod
    def idx2phn(idx):
        if -Phoneme.phn_num <= idx < Phoneme.phn_num:
            return Phoneme.phn_list[idx]
        return Phoneme.phn_list[0]
    
    @staticmethod
    def one_hot(phn):
        hot = [0. for _ in range(Phoneme.phn_num)]
        hot[Phoneme.phn2idx(phn)] = 1.
        return hot
    
    @staticmethod
    def is_vowel(phn):
        if phn is not None and len(phn) > 2:
            return phn[1] in "aoeiuv"
        return False


if __name__ == "__main__":
    
    print()
    

