# coding: utf-8

from .lang import Lang

class Syllable:
    syl_dict = {
        "a": ("aa",),
        "ai": ("ay", "ib",),
        "an": ("ae", "n",),
        "ang": ("ah", "ng",),
        "ao": ("ah", "ub",),
        "ba": ("b", "aa",),
        "bai": ("b", "ay", "ib",),
        "ban": ("b", "ae", "n",),
        "bang": ("b", "ah", "ng",),
        "bao": ("b", "ah", "ub",),
        "bei": ("b", "ei", "ib",),
        "ben": ("b", "ax", "n",),
        "beng": ("b", "oe", "ng",),
        "bi": ("b", "iy",),
        "bian": ("b", "il", "eh", "n",),
        "biao": ("b", "il", "ah", "ub",),
        "bie": ("b", "il", "ee",),
        "bin": ("b", "ih", "n",),
        "bing": ("b", "ih", "ng",),
        "bo": ("b", "ul", "ao",),
        "bu": ("b", "uw",),
        "ca": ("c", "aa",),
        "cai": ("c", "ay", "ib",),
        "can": ("c", "ae", "n",),
        "cang": ("c", "ah", "ng",),
        "cao": ("c", "ah", "ub",),
        "ce": ("c", "ea",),
        "cei": ("c", "ei", "ib",),
        "cen": ("c", "ax", "n",),
        "ceng": ("c", "oe", "ng",),
        "cha": ("ch", "aa",),
        "chai": ("ch", "ay", "ib",),
        "chan": ("ch", "ae", "n",),
        "chang": ("ch", "ah", "ng",),
        "chao": ("ch", "ah", "ub",),
        "che": ("ch", "ea",),
        "chen": ("ch", "ax", "n",),
        "cheng": ("ch", "oe", "ng",),
        "chi": ("ch", "izh",),
        "chong": ("ch", "oh", "ng",),
        "chou": ("ch", "oh", "ub",),
        "chu": ("ch", "uw",),
        "chua": ("ch", "ul", "aa",),
        "chuai": ("ch", "ul", "ay", "ib",),
        "chuan": ("ch", "ul", "ae", "n",),
        "chuang": ("ch", "ul", "ah", "ng",),
        "chui": ("ch", "ul", "ei", "ib",),
        "chun": ("ch", "ul", "ax", "n",),
        "chuo": ("ch", "ul", "ao",),
        "ci": ("c", "iz",),
        "cong": ("c", "oh", "ng",),
        "cou": ("c", "oh", "ub",),
        "cu": ("c", "uw",),
        "cuan": ("c", "ul", "ae", "n",),
        "cui": ("c", "ul", "ei", "ib",),
        "cun": ("c", "ul", "ax", "n",),
        "cuo": ("c", "ul", "ao",),
        "da": ("d", "aa",),
        "dai": ("d", "ay", "ib",),
        "dan": ("d", "ae", "n",),
        "dang": ("d", "ah", "ng",),
        "dao": ("d", "ah", "ub",),
        "de": ("d", "ea",),
        "dei": ("d", "ei", "ib",),
        "den": ("d", "ax", "n",),
        "deng": ("d", "oe", "ng",),
        "di": ("d", "iy",),
        "dia": ("d", "il", "aa",),
        "dian": ("d", "il", "eh", "n",),
        "diao": ("d", "il", "ah", "ub",),
        "die": ("d", "il", "ee",),
        "ding": ("d", "ih", "ng",),
        "diu": ("d", "il", "oh", "ub",),
        "dong": ("d", "oh", "ng",),
        "dou": ("d", "oh", "ub",),
        "du": ("d", "uw",),
        "duan": ("d", "ul", "ae", "n",),
        "dui": ("d", "ul", "ei", "ib",),
        "dun": ("d", "ul", "ax", "n",),
        "duo": ("d", "ul", "ao",),
        "e": ("ea",),
        "ei": ("ei", "ib",),
        "en": ("ax", "n",),
        "eng": ("oe", "ng",),
        "er": ("aar",),
        "fa": ("f", "aa",),
        "fan": ("f", "ae", "n",),
        "fang": ("f", "ah", "ng",),
        "fei": ("f", "ei", "ib",),
        "fen": ("f", "ax", "n",),
        "feng": ("f", "oe", "ng",),
        "fiao": ("f", "il", "ah", "ub",),
        "fo": ("f", "ul", "ao",),
        "fou": ("f", "oh", "ub",),
        "fu": ("f", "uw",),
        "ga": ("g", "aa",),
        "gai": ("g", "ay", "ib",),
        "gan": ("g", "ae", "n",),
        "gang": ("g", "ah", "ng",),
        "gao": ("g", "ah", "ub",),
        "ge": ("g", "ea",),
        "gei": ("g", "ei", "ib",),
        "gen": ("g", "ax", "n",),
        "geng": ("g", "oe", "ng",),
        "gong": ("g", "oh", "ng",),
        "gou": ("g", "oh", "ub",),
        "gu": ("g", "uw",),
        "gua": ("g", "ul", "aa",),
        "guai": ("g", "ul", "ay", "ib",),
        "guan": ("g", "ul", "ae", "n",),
        "guang": ("g", "ul", "ah", "ng",),
        "gui": ("g", "ul", "ei", "ib",),
        "gun": ("g", "ul", "ax", "n",),
        "guo": ("g", "ul", "ao",),
        "ha": ("h", "aa",),
        "hai": ("h", "ay", "ib",),
        "han": ("h", "ae", "n",),
        "hang": ("h", "ah", "ng",),
        "hao": ("h", "ah", "ub",),
        "he": ("h", "ea",),
        "hei": ("h", "ei", "ib",),
        "hen": ("h", "ax", "n",),
        "heng": ("h", "oe", "ng",),
        "hong": ("h", "oh", "ng",),
        "hou": ("h", "oh", "ub",),
        "hu": ("h", "uw",),
        "hua": ("h", "ul", "aa",),
        "huai": ("h", "ul", "ay", "ib",),
        "huan": ("h", "ul", "ae", "n",),
        "huang": ("h", "ul", "ah", "ng",),
        "hui": ("h", "ul", "ei", "ib",),
        "hun": ("h", "ul", "ax", "n",),
        "huo": ("h", "ul", "ao",),
        "ji": ("j", "iy",),
        "jia": ("j", "il", "aa",),
        "jian": ("j", "il", "eh", "n",),
        "jiang": ("j", "il", "ah", "ng",),
        "jiao": ("j", "il", "ah", "ub",),
        "jie": ("j", "il", "ee",),
        "jin": ("j", "ih", "n",),
        "jing": ("j", "ih", "ng",),
        "jiong": ("j", "il", "oh", "ng",),
        "jiu": ("j", "il", "oh", "ub",),
        "ju": ("j", "vw",),
        "juan": ("j", "vl", "eh", "n",),
        "jue": ("j", "vl", "ee",),
        "jun": ("j", "vl", "ih", "n",),
        "ka": ("k", "aa",),
        "kai": ("k", "ay", "ib",),
        "kan": ("k", "ae", "n",),
        "kang": ("k", "ah", "ng",),
        "kao": ("k", "ah", "ub",),
        "ke": ("k", "ea",),
        "kei": ("k", "ei", "ib",),
        "ken": ("k", "ax", "n",),
        "keng": ("k", "oe", "ng",),
        "kong": ("k", "oh", "ng",),
        "kou": ("k", "oh", "ub",),
        "ku": ("k", "uw",),
        "kua": ("k", "ul", "aa",),
        "kuai": ("k", "ul", "ay", "ib",),
        "kuan": ("k", "ul", "ae", "n",),
        "kuang": ("k", "ul", "ah", "ng",),
        "kui": ("k", "ul", "ei", "ib",),
        "kun": ("k", "ul", "ax", "n",),
        "kuo": ("k", "ul", "ao",),
        "lv": ("l", "vw",),
        "lve": ("l", "vl", "ee",),
        "lue": ("l", "vl", "ee",),
        "la": ("l", "aa",),
        "lai": ("l", "ay", "ib",),
        "lan": ("l", "ae", "n",),
        "lang": ("l", "ah", "ng",),
        "lao": ("l", "ah", "ub",),
        "le": ("l", "ea",),
        "lei": ("l", "ei", "ib",),
        "leng": ("l", "oe", "ng",),
        "li": ("l", "iy",),
        "lia": ("l", "il", "aa",),
        "lian": ("l", "il", "eh", "n",),
        "liang": ("l", "il", "ah", "ng",),
        "liao": ("l", "il", "ah", "ub",),
        "lie": ("l", "il", "ee",),
        "lin": ("l", "ih", "n",),
        "ling": ("l", "ih", "ng",),
        "liu": ("l", "il", "oh", "ub",),
        "lo": ("l", "ao",),
        "long": ("l", "oh", "ng",),
        "lou": ("l", "oh", "ub",),
        "lu": ("l", "uw",),
        "luan": ("l", "ul", "ae", "n",),
        "lun": ("l", "ul", "ax", "n",),
        "luo": ("l", "ul", "ao",),
        "ma": ("m", "aa",),
        "mai": ("m", "ay", "ib",),
        "man": ("m", "ae", "n",),
        "mang": ("m", "ah", "ng",),
        "mao": ("m", "ah", "ub",),
        "me": ("m", "ea",),
        "mei": ("m", "ei", "ib",),
        "men": ("m", "ax", "n",),
        "meng": ("m", "oe", "ng",),
        "mi": ("m", "iy",),
        "mian": ("m", "il", "eh", "n",),
        "miao": ("m", "il", "ah", "ub",),
        "mie": ("m", "il", "ee",),
        "min": ("m", "ih", "n",),
        "ming": ("m", "ih", "ng",),
        "miu": ("m", "il", "oh", "ub",),
        "mo": ("m", "ul", "ao",),
        "mou": ("m", "oh", "ub",),
        "mu": ("m", "uw",),
        "nv": ("n", "vw",),
        "nve": ("n", "vl", "ee",),
        "nue": ("n", "vl", "ee",),
        "na": ("n", "aa",),
        "nai": ("n", "ay", "ib",),
        "nan": ("n", "ae", "n",),
        "nang": ("n", "ah", "ng",),
        "nao": ("n", "ah", "ub",),
        "ne": ("n", "ea",),
        "nei": ("n", "ei", "ib",),
        "nen": ("n", "ax", "n",),
        "neng": ("n", "oe", "ng",),
        "ni": ("n", "iy",),
        "nian": ("n", "il", "eh", "n",),
        "niang": ("n", "il", "ah", "ng",),
        "niao": ("n", "il", "ah", "ub",),
        "nie": ("n", "il", "ee",),
        "nin": ("n", "ih", "n",),
        "ning": ("n", "ih", "ng",),
        "niu": ("n", "il", "oh", "ub",),
        "nong": ("n", "oh", "ng",),
        "nou": ("n", "oh", "ub",),
        "nu": ("n", "uw",),
        "nuan": ("n", "ul", "ae", "n",),
        "nun": ("n", "ul", "ax", "n",),
        "nuo": ("n", "ul", "ao",),
        "o": ("ao",),
        "ou": ("oh", "ub",),
        "pa": ("p", "aa",),
        "pai": ("p", "ay", "ib",),
        "pan": ("p", "ae", "n",),
        "pang": ("p", "ah", "ng",),
        "pao": ("p", "ah", "ub",),
        "pei": ("p", "ei", "ib",),
        "pen": ("p", "ax", "n",),
        "peng": ("p", "oe", "ng",),
        "pi": ("p", "iy",),
        "pian": ("p", "il", "eh", "n",),
        "piao": ("p", "il", "ah", "ub",),
        "pie": ("p", "il", "ee",),
        "pin": ("p", "ih", "n",),
        "ping": ("p", "ih", "ng",),
        "po": ("p", "ul", "ao",),
        "pou": ("p", "oh", "ub",),
        "pu": ("p", "uw",),
        "qi": ("q", "iy",),
        "qia": ("q", "il", "aa",),
        "qian": ("q", "il", "eh", "n",),
        "qiang": ("q", "il", "ah", "ng",),
        "qiao": ("q", "il", "ah", "ub",),
        "qie": ("q", "il", "ee",),
        "qin": ("q", "ih", "n",),
        "qing": ("q", "ih", "ng",),
        "qiong": ("q", "il", "oh", "ng",),
        "qiu": ("q", "il", "oh", "ub",),
        "qu": ("q", "vw",),
        "quan": ("q", "vl", "eh", "n",),
        "que": ("q", "vl", "ee",),
        "qun": ("q", "vl", "ih", "n",),
        "ran": ("r", "ae", "n",),
        "rang": ("r", "ah", "ng",),
        "rao": ("r", "ah", "ub",),
        "re": ("r", "ea",),
        "ren": ("r", "ax", "n",),
        "reng": ("r", "oe", "ng",),
        "ri": ("r", "izh",),
        "rong": ("r", "oh", "ng",),
        "rou": ("r", "oh", "ub",),
        "ru": ("r", "uw",),
        "rua": ("r", "ul", "aa",),
        "ruan": ("r", "ul", "ae", "n",),
        "rui": ("r", "ul", "ei", "ib",),
        "run": ("r", "ul", "ax", "n",),
        "ruo": ("r", "ul", "ao",),
        "sa": ("s", "aa",),
        "sai": ("s", "ay", "ib",),
        "san": ("s", "ae", "n",),
        "sang": ("s", "ah", "ng",),
        "sao": ("s", "ah", "ub",),
        "se": ("s", "ea",),
        "sei": ("s", "ei", "ib",),
        "sen": ("s", "ax", "n",),
        "seng": ("s", "oe", "ng",),
        "sha": ("sh", "aa",),
        "shai": ("sh", "ay", "ib",),
        "shan": ("sh", "ae", "n",),
        "shang": ("sh", "ah", "ng",),
        "shao": ("sh", "ah", "ub",),
        "she": ("sh", "ea",),
        "shei": ("sh", "ei", "ib",),
        "shen": ("sh", "ax", "n",),
        "sheng": ("sh", "oe", "ng",),
        "shi": ("sh", "izh",),
        "shou": ("sh", "oh", "ub",),
        "shu": ("sh", "uw",),
        "shua": ("sh", "ul", "aa",),
        "shuai": ("sh", "ul", "ay", "ib",),
        "shuan": ("sh", "ul", "ae", "n",),
        "shuang": ("sh", "ul", "ah", "ng",),
        "shui": ("sh", "ul", "ei", "ib",),
        "shun": ("sh", "ul", "ax", "n",),
        "shuo": ("sh", "ul", "ao",),
        "si": ("s", "iz",),
        "song": ("s", "oh", "ng",),
        "sou": ("s", "oh", "ub",),
        "su": ("s", "uw",),
        "suan": ("s", "ul", "ae", "n",),
        "sui": ("s", "ul", "ei", "ib",),
        "sun": ("s", "ul", "ax", "n",),
        "suo": ("s", "ul", "ao",),
        "ta": ("t", "aa",),
        "tai": ("t", "ay", "ib",),
        "tan": ("t", "ae", "n",),
        "tang": ("t", "ah", "ng",),
        "tao": ("t", "ah", "ub",),
        "te": ("t", "ea",),
        "tei": ("t", "ei", "ib",),
        "teng": ("t", "oe", "ng",),
        "ti": ("t", "iy",),
        "tian": ("t", "il", "eh", "n",),
        "tiao": ("t", "il", "ah", "ub",),
        "tie": ("t", "il", "ee",),
        "tin": ("t", "ih", "n",),
        "ting": ("t", "ih", "ng",),
        "tong": ("t", "oh", "ng",),
        "tou": ("t", "oh", "ub",),
        "tu": ("t", "uw",),
        "tuan": ("t", "ul", "ae", "n",),
        "tui": ("t", "ul", "ei", "ib",),
        "tun": ("t", "ul", "ax", "n",),
        "tuo": ("t", "ul", "ao",),
        "wa": ("w", "aa",),
        "wai": ("w", "ay", "ib",),
        "wan": ("w", "ae", "n",),
        "wang": ("w", "ah", "ng",),
        "wei": ("w", "ei", "ib",),
        "wen": ("w", "ax", "n",),
        "weng": ("w", "oe", "ng",),
        "wo": ("w", "ao",),
        "wu": ("w", "uw",),
        "xi": ("x", "iy",),
        "xia": ("x", "il", "aa",),
        "xian": ("x", "il", "eh", "n",),
        "xiang": ("x", "il", "ah", "ng",),
        "xiao": ("x", "il", "ah", "ub",),
        "xie": ("x", "il", "ee",),
        "xin": ("x", "ih", "n",),
        "xing": ("x", "ih", "ng",),
        "xiong": ("x", "il", "oh", "ng",),
        "xiu": ("x", "il", "oh", "ub",),
        "xu": ("x", "vw",),
        "xuan": ("x", "vl", "eh", "n",),
        "xue": ("x", "vl", "ee",),
        "xun": ("x", "vl", "ih", "n",),
        "ya": ("y", "aa",),
        "yan": ("y", "ae", "n",),
        "yang": ("y", "ah", "ng",),
        "yao": ("y", "ah", "ub",),
        "ye": ("y", "ee",),
        "yi": ("y", "iy",),
        "yin": ("y", "ih", "n",),
        "ying": ("y", "ih", "ng",),
        "yo": ("y", "ao",),
        "yong": ("y", "oh", "ng",),
        "you": ("y", "oh", "ub",),
        "yu": ("y", "vw",),
        "yuan": ("y", "vl", "eh", "n",),
        "yue": ("y", "vl", "ee",),
        "yun": ("y", "vl", "ih", "n",),
        "za": ("z", "aa",),
        "zai": ("z", "ay", "ib",),
        "zan": ("z", "ae", "n",),
        "zang": ("z", "ah", "ng",),
        "zao": ("z", "ah", "ub",),
        "ze": ("z", "ea",),
        "zei": ("z", "ei", "ib",),
        "zen": ("z", "ax", "n",),
        "zeng": ("z", "oe", "ng",),
        "zha": ("zh", "aa",),
        "zhai": ("zh", "ay", "ib",),
        "zhan": ("zh", "ae", "n",),
        "zhang": ("zh", "ah", "ng",),
        "zhao": ("zh", "ah", "ub",),
        "zhe": ("zh", "ea",),
        "zhei": ("zh", "ei", "ib",),
        "zhen": ("zh", "ax", "n",),
        "zheng": ("zh", "oe", "ng",),
        "zhi": ("zh", "izh",),
        "zhong": ("zh", "oh", "ng",),
        "zhou": ("zh", "oh", "ub",),
        "zhu": ("zh", "uw",),
        "zhua": ("zh", "ul", "aa",),
        "zhuai": ("zh", "ul", "ay", "ib",),
        "zhuan": ("zh", "ul", "ae", "n",),
        "zhuang": ("zh", "ul", "ah", "ng",),
        "zhui": ("zh", "ul", "ei", "ib",),
        "zhun": ("zh", "ul", "ax", "n",),
        "zhuo": ("zh", "ul", "ao",),
        "zi": ("z", "iz",),
        "zong": ("z", "oh", "ng",),
        "zou": ("z", "oh", "ub",),
        "zu": ("z", "uw",),
        "zuan": ("z", "ul", "ae", "n",),
        "zui": ("z", "ul", "ei", "ib",),
        "zun": ("z", "ul", "ax", "n",),
        "zuo": ("z", "ul", "ao",),
        "hm": ("h", "m",),
        "hng": ("h", "ng",),
        "m": ("m",),
        "ng": ("ng",),
        "kiu": ("k", "il", "oh", "ub",),
        "fai": ("f", "ay", "ib",),
        "bia": ("b", "il", "aa",),
        "biu": ("b", "il", "oh", "ub",),
        "gia": ("g", "il", "aa",),
        "giao": ("g", "il", "ah", "ub",),
        "giu": ("g", "il", "oh", "ub",),
        "hia": ("h", "il", "aa",),
        "hiao": ("h", "il", "ah", "ub",),
        "hiu": ("h", "il", "oh", "ub",),
        "kia": ("k", "il", "aa",),
        "kiao": ("k", "il", "ah", "ub",),
        "mia": ("m", "il", "aa",),
        "nia": ("n", "il", "aa",),
        "pia": ("p", "il", "aa",),
        "piu": ("p", "il", "oh", "ub",),
        "be": ("b", "ea",),
        "pe": ("p", "ea",),
        "bou": ("b", "oh", "ub",),
        "bua": ("b", "ul", "aa",),
        "cua": ("c", "ul", "aa",),
        "dua": ("d", "ul", "aa",),
        "lua": ("l", "ul", "aa",),
        "mua": ("m", "ul", "aa",),
        "nua": ("n", "ul", "aa",),
        "pua": ("p", "ul", "aa",),
        "sua": ("s", "ul", "aa",),
        "tua": ("t", "ul", "aa",),
        "bue": ("b", "vl", "ee",),
        "due": ("d", "vl", "ee",),
        "gue": ("g", "vl", "ee",),
        "hue": ("h", "vl", "ee",),
        "kue": ("k", "vl", "ee",),
        "mue": ("m", "vl", "ee",),
        "pue": ("p", "vl", "ee",),
        "sue": ("s", "vl", "ee",),
        "tue": ("t", "vl", "ee",),
        "wue": ("w", "vl", "ee",),
        "bui": ("b", "ul", "ei", "ib",),
        "jui": ("j", "ul", "ei", "ib",),
        "lui": ("l", "ul", "ei", "ib",),
        "mui": ("m", "ul", "ei", "ib",),
        "nui": ("n", "ul", "ei", "ib",),
        "pui": ("p", "ul", "ei", "ib",),
        "qui": ("q", "ul", "ei", "ib",),
        "xui": ("x", "ul", "ei", "ib",),
        "buo": ("b", "ul", "ao",),
        "juo": ("j", "ul", "ao",),
        "muo": ("m", "ul", "ao",),
        "puo": ("p", "ul", "ao",),
        "quo": ("q", "ul", "ao",),
        "gie": ("g", "il", "ee",),
        "hie": ("h", "il", "ee",),
        "kie": ("k", "il", "ee",),
        "tia": ("t", "il", "aa",),
        "tiu": ("t", "il", "oh", "ub",),
    }
    
    @staticmethod
    def s2p(syl):
        if Syllable.is_sil(syl):
            return ('sil',)
        if '(' in syl and ')' in syl:
            return tuple([f"{Lang.EN}{x}" for x in syl.strip('0123456789()').split('_')]) # (g_uh_d) -> ("ENg", "ENuh", "ENd')
        return tuple([f"{Lang.CN}{x}" for x in Syllable.syl_dict.get(syl, ('sil',))])
    
    @staticmethod
    def p2s(phs):
        if len(phs) == 1 and phs[0] == 'sil':
            return 'sil'
        if phs[0][:len(Lang.EN)] == Lang.EN:
            return '(' + "_".join([x[len(Lang.EN):] for x in phs]) + ')'
        for syl, phs_ in Syllable.syl_dict.items():
            if len(phs) == len(phs_) and all([x==y for x,y in zip(phs,phs_)]):
                return syl
        return 'sil'
    
    @staticmethod
    def is_py(syl):
        syl = syl.lower()
        return Syllable.is_sil(syl) or syl in Syllable.syl_dict
    
    @staticmethod
    def is_sil(syl):
        return syl.lower() in ('sil', 'sil0', '(sil)0')


if __name__ == "__main__":
    
    print(Syllable.s2p('sil'))
    
